### ISSUE TITLE
Poedit build failure regarding wxWebView

### ISSUE THREAD

**Issue by Vistaus** [vslavik/poedit#700]
I'm trying to compile from the latest git master on Debian and I've installed all of the necessary dependencies, including the dev files for wxWidgets WebView (GTK3), version 3.0.4. But for some reason, Poedit fails during make.

```
 13:29:29  ✘  ~/Downloads/poedit   master ✘ ✹ ✭ 
$ make -j7                                                                                             43s 515ms → 130 
Making all in src
make[1]: Entering folder '/home/thefish/Downloads/poedit/src'
  CXX      fileviewer.o
  CXX      manager.o
  CXX      prefsdlg.o
  CXX      pretranslate.o
  CXX      progressinfo.o
  CXX      propertiesdlg.o
  CXX      recent_files.o
In file included from progressinfo.h:30,
                 from manager.cpp:62:
titleless_window.h:32:24: warning: type attributes ignored after type is already defined [-Wattributes]
   32 | class WXDLLIMPEXP_CORE wxButton;
      |                        ^~~~~~~~
fileviewer.cpp: In constructor ‘FileViewer::FileViewer(wxWindow*)’:
fileviewer.cpp:141:28: error: incomplete type ‘wxWebView’ used in nested name specifier
  141 |     m_content = wxWebView::New(panel, wxID_ANY);
      |                            ^~~
fileviewer.cpp:142:16: error: invalid conversion from ‘wxWebView*’ to ‘int’ [-fpermissive]
  142 |     sizer->Add(m_content, 1, wxEXPAND);
      |                ^~~~~~~~~
      |                |
      |                wxWebView*
In file included from fileviewer.cpp:38:
/usr/include/wx-3.0/wx/sizer.h:1162:19: note:   initializing argument 1 of ‘wxSizerItem* wxSizer::Add(int, int, int, int, int, wxObject*)’
 1162 | wxSizer::Add( int width, int height, int proportion, int flag, int border, wxObject* userData )
      |               ~~~~^~~~~
fileviewer.cpp:151:17: error: invalid conversion from ‘wxWebView*’ to ‘size_t’ {aka ‘long unsigned int’} [-fpermissive]
  151 |     sizer->Hide(m_content);
      |                 ^~~~~~~~~
      |                 |
      |                 wxWebView*
In file included from fileviewer.cpp:38:
/usr/include/wx-3.0/wx/sizer.h:705:23: note:   initializing argument 1 of ‘bool wxSizer::Hide(size_t)’
  705 |     bool Hide( size_t index )
      |                ~~~~~~~^~~~~
fileviewer.cpp: In member function ‘void FileViewer::ShowHTMLContent(const wxString&)’:
fileviewer.cpp:302:14: error: invalid use of incomplete type ‘class wxWebView’
  302 |     m_content->GetContainingSizer()->Show(m_content);
      |              ^~
In file included from fileviewer.cpp:28:
fileviewer.h:39:28: note: forward declaration of ‘class wxWebView’
   39 | class WXDLLIMPEXP_FWD_CORE wxWebView;
      |                            ^~~~~~~~~
fileviewer.cpp:329:14: error: invalid use of incomplete type ‘class wxWebView’
  329 |     m_content->SetPage(markup, "file:///");
      |              ^~
In file included from fileviewer.cpp:28:
fileviewer.h:39:28: note: forward declaration of ‘class wxWebView’
   39 | class WXDLLIMPEXP_FWD_CORE wxWebView;
      |                            ^~~~~~~~~
In file included from progressinfo.h:30,
                 from pretranslate.cpp:31:
titleless_window.h:32:24: warning: type attributes ignored after type is already defined [-Wattributes]
   32 | class WXDLLIMPEXP_CORE wxButton;
      |                        ^~~~~~~~
make[1]: *** [Makefile:755: fileviewer.o] Error 1
make[1]: *** Waiting for unfinished tasks...
make[1]: Leaving folder '/home/thefish/Downloads/poedit/src'
make: *** [Makefile:484: all-recursive] Error 1

 13:30:12  ✘  ~/Downloads/poedit   master ✘ ✹ ✭ 
$   
```

What could be the issue and how do I solve this?

**Comment by vslavik** [comment]
As you can see
1. Poedit builds with wx-3.0, in an environment very similar to yours: https://travis-ci.org/github/vslavik/poedit/builds/772749903
2. The failing file does include the appropriate header which defines the symbol the `error: incomplete type ‘wxWebView’` message refers to: https://github.com/vslavik/poedit/blob/d712a7b8d6fdeb93ac44ae6c6956c1c4ab96be02/src/fileviewer.cpp#L45

> What could be the issue 
 
So that both points to some compilation mismatch at your end (multiple copies of wx, using the wrong one, messing with include paths or other flags etc.)

> and how do I solve this?

As always when you choose to compile from sources: investigate. It's happening on your computer, you have all the information you need to figure it out — unlike anybody else. Read configure's logs. Check the included files for why the symbol is not defined. Check `.d` files to see where the header is used from.  This will either lead to the conclusion that the build environment was messed up, and fixing it (experience says 99% of such issues are exactly that) or if not, such investigation will inform much better understanding of what is happening, with what wx version/config, and what needs fixing on Poedit's end.

But just from seeing how `wx/webview.h` is organized, I don't see any other possible explanation than `wxUSE_WEBVIEW` being set to 0, i.e. wx being without wxWebView.

**Comment by Vistaus** [comment]
I double-checked and there's only one WebView version installed, version 3.0.4
The build environment is clean.

What more information do you need to investigate this?

**Comment by vslavik** [comment]
> I double-checked […] The build environment is clean

You provide zero evidence of in-depth investigation ("double-checking") of the environment as I described above. If you have it, please do provide it, to actually rule out your environment, as I asked you to.

On the other hand, I did provide you pointers to specific places, with specific evidence of this error being implausible in a correct build environment with wxWebView enabled, including actual build logs.

Poedit does include the header that defines `wxWebView`. Yet, `wxWebView` is undefined and you get an error. The only explanation for that is that the header did not define the symbol even though it should. The only explanation for *that* is that `wxUSE_WEBVIEW` is off. Ergo, you either don't have wxWebView dev files installed (contrary to the initial claim) or you do have them, but they are not being used (i.e. multiple wx instances).

Think about it rationally. "It's all there and correct, but it magically disappears when the compiler looks at the file" is just not plausible.


> What more information do you need to investigate this?

This is something happening on *your* computer. *You* need to investigate it. I pointed you to specific files to inspect, including the `.d` files. It will points you to the header used, and to the `setup.h` header used. *Look at them*.

To be blunt, if you're not willing to look into things, you should use packages and shouldn't be compiling from sources, it's just wasting everybody's time (not least yours!). If you do want to compile from sources, you must be prepared to get your hands dirty a bit.

**Comment by Vistaus** [comment]
I figured it out: the issue lies in the 3.0.4 package Debian provides. With 3.1 in an equally clean environment, Poedit builds fine. I'll close this issue and file a bug report over at Debian. Thanks for the pointers, though!
